import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import { useState } from "react";
import { useForm } from "react-hook-form";
import GradeOutlinedIcon from '@mui/icons-material/GradeOutlined';
import GradeIcon from '@mui/icons-material/Grade';

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const books = api.book.list.useQuery();
  const users = api.user.list.useQuery();
  const user = api.user.get.useQuery();
  const bookFavs = api.bookFavs.getByUser.useQuery(
    undefined,
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          </div>
          <div className="flex flex-col items-center gap-2">

            {books.data && (
              <ul className="flex flex-col gap-2">
                {books.data.map((book) => (
                  <li key={book.id} className="text-white">
                    <div className="text-xl">{book.title}</div>
                    <div className="">{book.authors}</div>
                  <div onClick={}><GradeOutlinedIcon/></div>
                  
                  <GradeIcon/>
                  </li>
                ))}
              </ul>
            )}


            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const [editProfile, setEditProfile] = useState<boolean>(false);
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );
  const users = api.user.list.useQuery();
  const user = api.user.get.useQuery();
// useForm
  const { register, handleSubmit, watch, formState: { errors } } = useForm();
  const updateProfile = api.user.updateProfile.useMutation();
  const onSubmit = data => {
    console.log(data);
    if (data.profile) {
      updateProfile.mutate(
        {profile: data.profile},
      );

    }
    };
  const books = api.book.getByUser.useQuery(
    undefined,
    { enabled: sessionData?.user !== undefined },
  )


  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <Link href={`/users/`}>
        go to your page
      </Link>
      <div>
        {user.data?.name ?? "no user"}
      </div>
      {/* <div>
        {user.data?.profile ?? "no profile"}
      </div> */}
      {user.data?.image ? <img src={user.data?.image}>
      </img>: null}

      {books.data && (
        <ul className="flex flex-col gap-2">
          {books.data.map((book) => (
            <li key={book.id} className="text-white">
              <div className="text-xl">{book.title}</div>
              <div className="">{book.authors}</div>
              <div className="">{book.publisher}</div>
              <button onClick={() => {console.log("hello")}}>fav</button>
            </li>
          ))}
        </ul>
      )}






      {/* <button
        onClick={() => 
          {setEditProfile(!editProfile);
          }}>
        edit profile
      </button>
      {editProfile ? 

      <form onSubmit={handleSubmit(onSubmit)}>
        <input defaultValue="default" {...register("profile")}/>
        <input type="submit"/>
      </form> 
      : null
          } */}




      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
